CREATE TABLE IF NOT EXISTS inventory_equipments (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  name VARCHAR(255) NOT NULL,
  equipment_type VARCHAR(100) NOT NULL,
  serial_number VARCHAR(100),
  status VARCHAR(50) NOT NULL DEFAULT 'Ativo',
  location VARCHAR(255),
  created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);
